export const RESTART_AUTH_RESPONSE = "RESTART_AUTH_RESPONSE";
// user reducer types
export const LOADING_USER = "LOADING_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const SET_AUTH_USER = "SET_AUTH_USER";
// UI reducer types
export const SET_LOGIN_ERRORS = "SET_LOGIN_ERRORS";
export const SET_SIGNUP_ERRORS = "SET_SIGNUP_ERRORS";
export const DISPLAY_ERROR_MSG = "DISPLAY_ERROR_MSG";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SEND_TWEET_SUCCESS = "SEND_TWEET_SUCCESS";
export const CLOSE_TWEET_SUCCESS = "CLOSE_TWEET_SUCCESS";
export const SEND_TWEET_ERROR = "SEND_TWEET_ERROR";
// Tweet reducer types
export const SET_TWEET_TEXT = "SET_TWEET_TEXT";
export const SET_TWEET_PHOTO = "SET_TWEET_PHOTO";
export const SET_TWEET_DATA = "SET_TWEET_DATA";
export const LIKE_TWEET = "LIKE_TWEET";
export const UNLIKE_TWEET = "UNLIKE_TWEET";
export const CLEAR_FIELDS = "CLEAR_FIELDS";
export const CLOSE_TWEET_BOX = "CLOSE_TWEET_BOX";
export const OPEN_TWEET_BOX = "OPEN_TWEET_BOX";
export const FETCH_TWEET = "FETCH_TWEET";
export const FETCH_TWEET_LIKES = "FETCH_TWEET_LIKES";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const CODE_ERROR = "CODE_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
export const LOAD_TWEETS_SUCCESS = "LOAD_TWEETS_SUCCESS";
export const LOAD_TWEETS_ERROR = "LOAD_TWEETS_ERROR";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_ERROR = "LOAD_PROFILE_ERROR";
